services:
  - type: web
    name: portfolio-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    runtime: python
    pythonVersion: 3.10.13
    plan: free
    autoDeploy: true
